job:
  name: test-v4
  env_type: docker
  loop: true
  remote_user: zephyr

tpu:
  allocation_mode: "tpu-vm"    # tpu-vm | queued-resources
  accelerator: v4-128
  name: yufeng-${tpu.accelerator}
  zone: us-central2-b
  version: tpu-ubuntu2204-base
  pricing: spot
  # spot | ondemand | preemptible
  flags: []

gcsfuse:
  bucket_name: llm_pruning_us_central2_b
  mount_path: /home/zephyr/gcs-bucket

ssh:
  private_key: ~/.ssh/id_rsa
  identities:
    - private_key: ~/.ssh/id_rsa
      public_key: ~/.ssh/id_rsa.pub
      config_entry: | 
        Host 10.*
          IdentityFile ~/.ssh/id_rsa
          IdentitiesOnly yes
    - private_key: ~/.ssh/id_ed25519_github
      public_key: ~/.ssh/id_ed25519_github.pub
      config_entry: |
        Host github.com
          User git
          IdentityFile ~/.ssh/id_ed25519_github
          IdentitiesOnly yes

docker:
  image: yx3038/maxtext_base_image:latest
  flags: 
    - "--privileged"
    - "--network=host"
    - "--env HOME=/home/zephyr"
    - "-v /home/zephyr:/home/zephyr"
    - "-v /dev:/dev"
    - "-v /run:/run"
    - "-v /home/zephyr/.config/gcloud:/root/.config/gcloud"
    - "-w /home/zephyr"

conda:
  name: fms
  config_file: assets/fms.yaml

venv:
  name: maxtext
  requirements_file: assets/requirements.txt  
  python: "3.9"  

command:
  cmd: |
    
    gcloud config set project vision-mix

    gcloud config set compute/zone ${tpu.zone}

    export TPU_PREFIX=${tpu.name}

    export BUCKET_NAME=${gcsfuse.bucket_name}

    cd /home/zephyr/

    cd maxtext &&  git config pull.rebase false && git pull origin v6e || (git clone -b v6e https://github.com/Zephyr271828/maxtext.git && cd maxtext)

    bash scripts/llama3.1_4b_width_S50_1e-4_warmup_0.1.sh

    # export HF_DATASETS_CACHE='/home/zephyr/gcs-bucket/datasets'
    # cd /home/zephyr/gcs-bucket/lm-evaluation-harness
    # bash scripts/test_orbax_eval.sh
  workers: [0] # int | list | "all"