job:
  name: test-v4
  env_type: docker
  loop: true

tpu:
  allocation_mode: "queued-resources"    # tpu-vm | queued-resources
  accelerator: v4-8
  name: yufeng-${tpu.accelerator}
  zone: us-central2-b
  version: tpu-ubuntu2204-base
  pricing: spot
  # spot | ondemand | preemptible
  startup_script: null
  tags: ["jobman", "experiment"]
  metadata:
    owner: "yufeng"
    # owner can be used to map tpus to user I think
    purpose: "pretrain"

gcsfuse:
  bucket_name: llm_pruning_us_central2_b
  mount_path: /home/zephyr/gcs-bucket

ssh:
  private_key: ~/.ssh/id_rsa
  identities:
    - private_key: ~/.ssh/id_rsa
      public_key: ~/.ssh/id_rsa.pub
      config_entry: | 
        Host 10.*
          IdentityFile ~/.ssh/id_rsa
          IdentitiesOnly yes
    - private_key: ~/.ssh/id_ed25519_github
      public_key: ~/.ssh/id_ed25519_github.pub
      config_entry: |
        Host github.com
          User git
          IdentityFile ~/.ssh/id_ed25519_github
          IdentitiesOnly yes

docker:
  image: yx3038/maxtext_base_image:latest
  env_vars:
    - HOME=/home/zephyr
  mount_dirs:
    - /home/zephyr
    - /dev
    - /run
    - /home/zephyr/.config/gcloud:/root/.config/gcloud
    # - /home/zephyr/.ssh:/root/.ssh
  workdir: /home/zephyr
  flags: ["--privileged", "--network=host"]

conda:
  name: fms
  config_file: assets/fms.yaml

venv:
  name: maxtext
  requirements_file: assets/requirements.txt  
  python: "3.9"  

command:
  cmd: |
    
    gcloud config set project vision-mix

    gcloud config set compute/zone ${tpu.zone}

    export TPU_PREFIX=${tpu.name}

    export BUCKET_NAME=${gcsfuse.bucket_name}

    cd /home/zephyr/

    if [ -d 'maxtext/.git' ]; then
      echo '[INFO] maxtext already exists, pulling latest changes...''
      cd maxtext
      git pull origin v6e
    else
      echo '[INFO] Cloning maxtext repository...'
      git clone -b v6e https://github.com/Zephyr271828/maxtext.git
      cd maxtext
    fi

    bash scripts/llama3.1_4b_width_S50_1e-4_warmup_0.1.sh

    # export HF_DATASETS_CACHE='/home/zephyr/gcs-bucket/datasets'
    # cd /home/zephyr/gcs-bucket/lm-evaluation-harness
    # bash scripts/test_orbax_eval.sh
  workers: [0] # int | list | "all"