job:
  name: test-v6
  env_type: docker
  loop: False
  remote_user: zephyr

tpu:
  allocation_mode: "queued-resources"    # tpu-vm | queued-resources
  accelerator: v6e-4
  name: yufeng-${tpu.accelerator}
  zone: europe-west4-a
  version: v2-alpha-tpuv6e
  pricing: spot                   
  # spot | ondemand | preemptible
  flags: []

gcsfuse:
  bucket_name: llm_pruning_europe_west4
  mount_path: /home/zephyr/gcs-bucket

ssh:
  private_key: ~/.ssh/id_rsa
  identities:
    - private_key: ~/.ssh/id_rsa
      public_key: ~/.ssh/id_rsa.pub
      config_entry: | 
        Host 10.*
          IdentityFile ~/.ssh/id_rsa
          IdentitiesOnly yes
    - private_key: ~/.ssh/id_ed25519_github
      public_key: ~/.ssh/id_ed25519_github.pub
      config_entry: |
        Host github.com
          User git
          IdentityFile ~/.ssh/id_ed25519_github
          IdentitiesOnly yes

docker:
  image: yx3038/maxtext_base_image:latest
  flags: 
    - "--privileged"
    - "--network=host"
    - "--env HOME=/home/zephyr"
    - "-v /home/zephyr:/home/zephyr"
    - "-v /dev:/dev"
    - "-v /run:/run"
    - "-v /home/zephyr/.config/gcloud:/root/.config/gcloud"
    - "-w /home/zephyr"

conda:
  name: fms
  config_file: assets/fms.yaml

venv:
  name: maxtext
  requirements_file: assets/requirements.txt  
  python: "3.9"  

command:
  cmd: |

    gcloud config set project vision-mix

    gcloud config set compute/zone ${tpu.zone}

    export TPU_PREFIX=${tpu.name}

    export BUCKET_NAME=${gcsfuse.bucket_name}

    cd /home/zephyr/

    cd maxtext &&  git config pull.rebase false && git pull origin test || (git clone -b test https://github.com/Zephyr271828/maxtext.git && cd maxtext)

    bash scripts/llama3.1_4b_width_S50.sh

    # pip install torch
    # cd /home/zephyr/gcs-bucket/maxtext
    # bash tests/test_eq.sh    
  workers: [0] # int | list | "all"